options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/affordable-to-whom-img:$SHORT_SHA',
        '.'
      ]

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/affordable-to-whom-img:$SHORT_SHA'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'affordable-to-whom-app',               # Cloud Run service name
        '--image', 'gcr.io/$PROJECT_ID/affordable-to-whom-img:$SHORT_SHA', # Use the image we just pushed
        '--platform', 'managed',
        '--region', 'us-central1',                     # Replace with your region
        '--allow-unauthenticated',                     # Make public; remove if you want auth
        '--port', '8501'
      ]

images:
  - 'gcr.io/$PROJECT_ID/affordable-to-whom-img'